package cc.sfclub.packyserver.enum

enum class Type {
    USER_NOT_FOUND, PERMISSION_DENIED, WRONG_PASSWORD_OR_NAME, PACKAGE_NOT_FOUND, CAPTCHA_INCORRECT, PACKAGE_FOUND, INVALID_ERROR, GPG_SIGNATURE_INVALID, SUCCESS, CAPTCHA_CHECK_FAILED, USER_EXISTED
}